apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app: dev
spec:
  containers:
  - name: hello-service
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
