version: "3"

services:
  docker:
    image: uifd/ui-for-docker
    ports:
      - 8001:9000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 2

  portainer:
    image: portainer/portainer:latest
    ports:
      - 8002:9000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]