apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  replicas: 2
  selector:
    name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
